import {
  MD3LightTheme,
  MD3DarkTheme,
  adaptNavigationTheme,
  configureFonts,
} from 'react-native-paper';
import { DefaultTheme, DarkTheme } from '@react-navigation/native';
import { colors } from '@styles/colors';

const fontConfig = {
  displayLarge: {
    fontFamily: 'System',
    fontSize: 57,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: 'System',
    fontSize: 45,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: 'System',
    fontSize: 36,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLarge: {
    fontFamily: 'System',
    fontSize: 32,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: 'System',
    fontSize: 28,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: 'System',
    fontSize: 24,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: 'System',
    fontSize: 22,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '500' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMedium: {
    fontFamily: 'System',
    fontSize: 12,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: 'System',
    fontSize: 11,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  bodyLarge: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '400' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '400' as const,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: 'System',
    fontSize: 12,
    fontWeight: '400' as const,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
};

export const lightTheme = {
  ...MD3LightTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary[500],
    primaryContainer: colors.primary[100],
    secondary: colors.secondary[500],
    secondaryContainer: colors.secondary[100],
    tertiary: colors.primary[700],
    tertiaryContainer: colors.primary[200],
    surface: colors.common.white,
    surfaceVariant: colors.grey[100],
    surfaceDisabled: colors.grey[200],
    background: colors.background.light,
    error: colors.error.main,
    errorContainer: '#FFCDD2',
    onPrimary: colors.common.white,
    onPrimaryContainer: colors.primary[900],
    onSecondary: colors.common.white,
    onSecondaryContainer: colors.secondary[900],
    onTertiary: colors.common.white,
    onTertiaryContainer: colors.primary[900],
    onSurface: colors.text.primary.light,
    onSurfaceVariant: colors.text.secondary.light,
    onSurfaceDisabled: colors.text.disabled.light,
    onError: colors.common.white,
    onErrorContainer: colors.error.dark,
    onBackground: colors.text.primary.light,
    outline: colors.grey[400],
    outlineVariant: colors.grey[200],
    inverseSurface: colors.grey[900],
    inverseOnSurface: colors.common.white,
    inversePrimary: colors.primary[200],
    shadow: colors.common.black,
    scrim: colors.common.black,
    backdrop: 'rgba(0, 0, 0, 0.5)',
    elevation: {
      level0: 'transparent',
      level1: colors.grey[50],
      level2: colors.grey[100],
      level3: colors.grey[100],
      level4: colors.grey[200],
      level5: colors.grey[200],
    },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3DarkTheme.colors,
    primary: colors.primary[300],
    primaryContainer: colors.primary[800],
    secondary: colors.secondary[300],
    secondaryContainer: colors.secondary[800],
    tertiary: colors.primary[200],
    tertiaryContainer: colors.primary[700],
    surface: colors.grey[900],
    surfaceVariant: colors.grey[800],
    surfaceDisabled: colors.grey[700],
    background: colors.background.dark,
    error: colors.error.light,
    errorContainer: '#B71C1C',
    onPrimary: colors.primary[900],
    onPrimaryContainer: colors.primary[100],
    onSecondary: colors.secondary[900],
    onSecondaryContainer: colors.secondary[100],
    onTertiary: colors.primary[900],
    onTertiaryContainer: colors.primary[100],
    onSurface: colors.text.primary.dark,
    onSurfaceVariant: colors.text.secondary.dark,
    onSurfaceDisabled: colors.text.disabled.dark,
    onError: colors.error.dark,
    onErrorContainer: colors.error.light,
    onBackground: colors.text.primary.dark,
    outline: colors.grey[600],
    outlineVariant: colors.grey[700],
    inverseSurface: colors.grey[100],
    inverseOnSurface: colors.grey[900],
    inversePrimary: colors.primary[700],
    shadow: colors.common.black,
    scrim: colors.common.black,
    backdrop: 'rgba(0, 0, 0, 0.7)',
    elevation: {
      level0: 'transparent',
      level1: colors.grey[900],
      level2: colors.grey[800],
      level3: colors.grey[800],
      level4: colors.grey[700],
      level5: colors.grey[700],
    },
  },
};

export const { LightTheme: NavigationLightTheme, DarkTheme: NavigationDarkTheme } =
  adaptNavigationTheme({
    reactNavigationLight: DefaultTheme,
    reactNavigationDark: DarkTheme,
    materialLight: lightTheme,
    materialDark: darkTheme,
  });

export type AppTheme = typeof lightTheme;
